### ISSUE TITLE
Share Button: Track if the post is shared in share components

### ISSUE THREAD

**Issue by utkarshsanjivan** [caspg/react-sharingbuttons#6]
I want to track if the user posts in the social media platform after clicking on the share button for that social media.

Suppose a user  is on the webpage and clicks on the facebook sharing button and the component for sharing in facebook opens up.

![Screen Shot 2019-10-15 at 2 56 06 PM](https://user-images.githubusercontent.com/35485647/66819634-f51f2700-ef5c-11e9-83dd-e5da96ee1bed.png)

I just want to know if the user shares the post once he comes to above page.

**Comment by caspg** [comment]
This is not supported. The main point of this project was not to include any tracking code from social networks.

**Comment by utkarshsanjivan** [comment]
Thanks @caspg for the clarification.
